spring:
  data:
    mongodb:  
    #  host: http://mongodb-squall.7e14.starter-us-west-2.openshiftapps.com #192.168.99.100
     # port: 27017
      #database: cloud
     # username: user1EU
     # password: 1EyG0eQDx5sH62Lx
      uri: mongodb://user1EU:1EyG0eQDx5sH62Lx@mongodb-squall.7e14.starter-us-west-2.openshiftapps.com:27017/cloud
      
  datasource:
    driverClassName: com.mongodb.Mongo
      
server:
  contextPath: /squall 