spring:
  data:
    mongodb:  
     # host: 192.168.99.100
     # port: 27017
     # database: cloud
     # username: user1EU
     # password: 1EyG0eQDx5sH62Lx
      uri: mongodb://pipo2:pipo@ds127101.mlab.com:27101/cloud
      
  datasource:
    driverClassName: com.mongodb.Mongo
      
server:
  contextPath: /squall 
